// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryOperationKind = "recall" | "remember" | "update" | "drop" | "lessons" | "crystals" | "crystallize" | "auto_crystallize" | "insights" | "reflect" | "actions" | "action_create" | "action_update" | "frontier" | "next";
