// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryOperationKind } from "./MemoryOperationKind";
import type { MemoryOperationSource } from "./MemoryOperationSource";
import type { MemoryOperationStatus } from "./MemoryOperationStatus";

export type MemoryOperationNotification = { threadId: string, source: MemoryOperationSource, operation: MemoryOperationKind, status: MemoryOperationStatus, query: string | null, summary: string, detail: string | null, contextInjected: boolean, };
